### PR TITLE
Converted gradle files to use kts.

### PR DESCRIPTION
**Pull request by MrBergin**
Redone this pull request, this branch is mostly the same but without the directory restructuring so there's less chance of merge conflicts.

### CODE REVIEW

**Comment by MrBergin** [comment]
My guess would be this happened as a result of running gradlew wrapper --gradle-version 5.6.2.

Can't verify this right now but can try and replicate running it against current master locally and seeing how it changes it, honestly I've often just committed these files automatically in the past and assumed it's part of the gradle upgrade process! I'll clue myself in another day to provide a more satisfactory answer.

**Comment by adam-arold** [comment]
It sometimes happened to me as well that I used the refactor feature which accidentally tampered with files I didn't want to tamper with. In this case though it is very much possible that this change is there because you upped the version.

**Comment by MrBergin** [comment]
So it does look to be automatically added in after upgrading the version.

How would you like to proceed? Accept the auto generated changes or leave these files untouched? The changes look inconsequential to me.

**Comment by adam-arold** [comment]
I'd leave it as-is. They probably upgraded something. We can merge this!

**Comment by MrBergin** [comment]
Why can't I party parrot on github!  🎉

**Comment by adam-arold** [comment]
Open a PR with the parrot to their repo. 😂

**Pull request merged**
